[[plugins]]
repo = 'beyondmarc/hlsl.vim'
on_ft = ['hlsl']

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
build = 'git submodule update --init --recursive'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']
