[[plugins]]
repo = 'beyondmarc/hlsl.vim'
on_ft = ['hlsl']

[[plugins]]
repo = 'kmnk/vim-csharp'
on_ft = ['cs']

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']
