# init {{{
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'Shougo/dpp.vim'
rev = 'f9ba3e38e5a6c7b2bbe5e122de80483607435380'
[[plugins]]
repo = 'Shougo/dpp-ext-installer'
[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
[[plugins]]
repo = 'Shougo/dpp-ext-toml'
[[plugins]]
repo = 'Shougo/dpp-protocol-git'
# }}}

# ddu {{{
[[plugins]]
repo = 'Shougo/ddu.vim'
rev = '30481cb2183a8d08c677d3c0e6eac16a00dd9638'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'

# ddu ui {{{
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
[[plugins]]
repo = 'Shougo/ddu-column-filename'
# }}}

# ddu source {{{
[[plugins]]
repo = 'Shougo/ddu-source-action'
[[plugins]]
repo = 'Shougo/ddu-source-file'
[[plugins]]
repo = 'Shougo/ddu-source-file_old'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
[[plugins]]
repo = 'Shougo/ddu-source-line'
[[plugins]]
repo = 'Shougo/ddu-source-register'
[[plugins]]
repo = '4513ECHO/ddu-source-colorscheme'
[[plugins]]
repo = 'matsui54/ddu-source-help'
[[plugins]]
repo = 'matsui54/ddu-source-man'
[[plugins]]
repo = 'liquidz/ddu-source-custom-list'
[[plugins]]
repo = 'kuuote/ddu-source-mr'
rev = 'd1e90a38d0ba5ad34adcd132f98a9399baea3aa2'
# }}}

# ddu kind {{{
[[plugins]]
repo = 'Shougo/ddu-kind-file'
[[plugins]]
repo = 'Shougo/ddu-kind-word'
# }}}

# ddu filter {{{
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_relative'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
# }}}
# }}}

# ddc {{{
[[plugins]]
repo = 'Shougo/ddc.vim'

# ddc source {{{
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
[[plugins]]
repo = 'Shougo/ddc-omni'
[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
[[plugins]]
repo = 'LumaKernel/ddc-file'
# }}}

# ddc ui {{{
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
[[plugins]]
repo = 'Shougo/pum.vim'
# }}}
# }}}

[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo ='tpope/vim-fugitive'
[[plugins]]
repo ='tpope/vim-surround'
[[plugins]]
repo ='tpope/vim-repeat'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = 'kana/vim-submode'
[[plugins]]
repo = 'kana/vim-operator-replace'
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'h1mesuke/textobj-wiw'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'phaazon/hop.nvim'

# schema {{
[[plugins]]
repo = 'nelsyeung/twig.vim'
[[plugins]]
repo = 'mxw/vim-jsx'
# }}}

# kmnk {{{
[[plugins]]
repo = 'kmnk/denite-dirmark'
[[plugins]]
repo = 'kmnk/gitn'
[[plugins]]
repo = 'kmnk/denite-cmdl'
[[plugins]]
repo = 'kmnk/ddu-source-git'
rev = 'feature/make-core/devel'
# }}}

# on_ft {{{
[[plugins]]
repo = 'phpactor/phpactor'
lazy = true
on_ft = 'php'
build = 'composer install'

[[plugins]]
repo = 'rust-lang/rust.vim'
lazy = true
on_ft = 'rust'

[[plugins]]
repo = 'fatih/vim-go'
lazy = true
on_ft = 'go'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
lazy = true
on_ft = 'coffee'

[[plugins]]
repo = 'leafgarland/typescript-vim'
lazy = true
on_ft = 'typescript'
# }}}
