[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
